import { WispDocument, ScreenNode, WispNode } from "./types";

/**
 * Escapes Kotlin string literals
 */
function escapeKotlin(str: string): string {
  return String(str || "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, "\\$");
}

/**
 * Capitalizes a string to PascalCase for Kotlin Composable names
 */
function toPascalCase(str: string): string {
  return (str || "Main")
    .replace(/[^a-zA-Z0-9]/g, " ")
    .split(" ")
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("") || "Screen";
}

/**
 * Maps icon name to standard Material Icon Vector in Jetpack Compose
 */
function mapComposeIcon(name?: string): string {
  const n = (name || "star").toLowerCase();
  if (n.includes("user") || n.includes("person") || n.includes("account")) return "Icons.Default.Person";
  if (n.includes("home")) return "Icons.Default.Home";
  if (n.includes("search")) return "Icons.Default.Search";
  if (n.includes("setting")) return "Icons.Default.Settings";
  if (n.includes("bell") || n.includes("notif")) return "Icons.Default.Notifications";
  if (n.includes("mail") || n.includes("email")) return "Icons.Default.Email";
  if (n.includes("lock") || n.includes("key")) return "Icons.Default.Lock";
  if (n.includes("check")) return "Icons.Default.Check";
  if (n.includes("add") || n.includes("plus")) return "Icons.Default.Add";
  if (n.includes("arrow-right") || n.includes("forward")) return "Icons.AutoMirrored.Filled.ArrowForward";
  if (n.includes("arrow-left") || n.includes("back")) return "Icons.AutoMirrored.Filled.ArrowBack";
  if (n.includes("close") || n.includes("clear") || n.includes("x")) return "Icons.Default.Close";
  if (n.includes("menu")) return "Icons.Default.Menu";
  if (n.includes("edit")) return "Icons.Default.Edit";
  if (n.includes("delete") || n.includes("trash")) return "Icons.Default.Delete";
  if (n.includes("refresh")) return "Icons.Default.Refresh";
  if (n.includes("info")) return "Icons.Default.Info";
  if (n.includes("warning") || n.includes("alert")) return "Icons.Default.Warning";
  if (n.includes("star") || n.includes("fav")) return "Icons.Default.Star";
  if (n.includes("share")) return "Icons.Default.Share";
  if (n.includes("filter")) return "Icons.Default.FilterList";
  if (n.includes("time") || n.includes("clock")) return "Icons.Default.DateRange";
  return "Icons.Default.Star";
}

/**
 * Generates Jetpack Compose Material 3 Kotlin code from a Wisp Document AST.
 */
export function exportToJetpackCompose(doc: WispDocument): string {
  const standardScreens = doc.screens.filter(
    s => s.type !== "dialog" && s.type !== "modal" && s.type !== "sheet" && s.type !== "component"
  );
  const modalScreens = doc.screens.filter(
    s => s.type === "dialog" || s.type === "modal" || s.type === "sheet"
  );
  const firstScreen = standardScreens[0]?.name || "Home";

  let out = `package com.example.m3expressive

import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.*
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * Material 3 Expressive Theme Application Prototype
 * Generated by Wisp Studio for Jetpack Compose
 */
@Composable
fun WispAppTheme(
    darkTheme: Boolean = false,
    content: @Composable () -> Unit
) {
    val colorScheme = if (darkTheme) {
        darkColorScheme(
            primary = Color(0xFFD0BCFF),
            onPrimary = Color(0xFF381E72),
            primaryContainer = Color(0xFF4F378B),
            onPrimaryContainer = Color(0xFFEADDFF),
            secondary = Color(0xFFCCC2DC),
            onSecondary = Color(0xFF332D41),
            secondaryContainer = Color(0xFF4A4458),
            onSecondaryContainer = Color(0xFFE8DEF8),
            tertiary = Color(0xFFEFB8C8),
            onTertiary = Color(0xFF492532),
            tertiaryContainer = Color(0xFF633B48),
            onTertiaryContainer = Color(0xFFFFD8E4),
            surface = Color(0xFF141218),
            onSurface = Color(0xFFE6E1E5),
            surfaceVariant = Color(0xFF49454F),
            onSurfaceVariant = Color(0xFFCAC4D0),
            surfaceContainer = Color(0xFF211F26),
            surfaceContainerHigh = Color(0xFF2B2930),
            outline = Color(0xFF938F99),
            outlineVariant = Color(0xFF44474F)
        )
    } else {
        lightColorScheme(
            primary = Color(0xFF6750A4),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFEADDFF),
            onPrimaryContainer = Color(0xFF21005D),
            secondary = Color(0xFF625B71),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE8DEF8),
            onSecondaryContainer = Color(0xFF1D192B),
            tertiary = Color(0xFF7D5260),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFFD8E4),
            onTertiaryContainer = Color(0xFF31111D),
            surface = Color(0xFFFEF7FF),
            onSurface = Color(0xFF1D1B20),
            surfaceVariant = Color(0xFFE7E0EC),
            onSurfaceVariant = Color(0xFF49454F),
            surfaceContainer = Color(0xFFF3EDF7),
            surfaceContainerHigh = Color(0xFFECE6F0),
            outline = Color(0xFF79747E),
            outlineVariant = Color(0xFFCAC4D0)
        )
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography(),
        content = content
    )
}

/**
 * Main Application Prototype with Navigation & State Management
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AppPrototype() {
    var currentScreen by remember { mutableStateOf("${escapeKotlin(firstScreen)}") }
    var activeModal by remember { mutableStateOf<String?>(null) }
    var wizardStep by remember { mutableIntStateOf(1) }
    val formData = remember { mutableStateMapOf<String, Any>() }

    WispAppTheme {
        Scaffold(
            containerColor = MaterialTheme.colorScheme.surface,
            contentColor = MaterialTheme.colorScheme.onSurface
        ) { innerPadding ->
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
            ) {
                // Screen Content Routing
                when (currentScreen) {
`;

  // Generate routing cases
  for (const s of standardScreens) {
    const fnName = `${toPascalCase(s.name)}Screen`;
    out += `                    "${escapeKotlin(s.name)}" -> {\n`;
    out += `                        ${fnName}(\n`;
    out += `                            onNavigate = { target ->\n`;
    out += `                                if (target.startsWith("@")) {\n`;
    out += `                                    val screenTarget = target.removePrefix("@").substringBefore("?")\n`;
    out += `                                    currentScreen = screenTarget\n`;
    out += `                                }\n`;
    out += `                            },\n`;
    out += `                            onOpenModal = { modal -> activeModal = modal },\n`;
    out += `                            wizardStep = wizardStep,\n`;
    out += `                            onStepChange = { step -> wizardStep = step },\n`;
    out += `                            formData = formData\n`;
    out += `                        )\n`;
    out += `                    }\n`;
  }

  out += `                    else -> {\n`;
  out += `                        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {\n`;
  out += `                            Text("Pantalla '$currentScreen' no encontrada", style = MaterialTheme.typography.bodyLarge)\n`;
  out += `                        }\n`;
  out += `                    }\n`;
  out += `                }\n\n`;

  // Render Modal Dialogs
  if (modalScreens.length > 0) {
    out += `                // Modals & Bottom Sheets\n`;
    for (const m of modalScreens) {
      out += `                if (activeModal == "${escapeKotlin(m.name)}") {\n`;
      out += `                    AlertDialog(\n`;
      out += `                        onDismissRequest = { activeModal = null },\n`;
      out += `                        title = {\n`;
      out += `                            Text(\n`;
      out += `                                text = "${escapeKotlin(m.props.title || m.name)}",\n`;
      out += `                                style = MaterialTheme.typography.headlineSmall,\n`;
      out += `                                fontWeight = FontWeight.Bold\n`;
      out += `                            )\n`;
      out += `                        },\n`;
      out += `                        text = {\n`;
      out += `                            Column(modifier = Modifier.fillMaxWidth().verticalScroll(rememberScrollState()), verticalArrangement = Arrangement.spacedBy(12.dp)) {\n`;
      out += renderComposeNodes(m.children, 8);
      out += `                            }\n`;
      out += `                        },\n`;
      out += `                        confirmButton = {\n`;
      out += `                            Button(onClick = { activeModal = null }) {\n`;
      out += `                                Text("Aceptar")\n`;
      out += `                            }\n`;
      out += `                        },\n`;
      out += `                        dismissButton = {\n`;
      out += `                            TextButton(onClick = { activeModal = null }) {\n`;
      out += `                                Text("Cerrar")\n`;
      out += `                            }\n`;
      out += `                        }\n`;
      out += `                    )\n`;
      out += `                }\n`;
    }
  }

  out += `            }\n`;
  out += `        }\n`;
  out += `    }\n`;
  out += `}\n\n`;

  // Generate Individual Screen Composables
  for (const s of standardScreens) {
    out += generateScreenComposable(s);
  }

  out += `\n@Preview(showBackground = true, widthDp = 412, heightDp = 892)\n`;
  out += `@Composable\n`;
  out += `fun AppPrototypePreview() {\n`;
  out += `    AppPrototype()\n`;
  out += `}\n`;

  return out;
}

/**
 * Generates an individual Screen Composable function.
 */
function generateScreenComposable(screen: ScreenNode): string {
  const fnName = `${toPascalCase(screen.name)}Screen`;
  const isWizard = screen.type === "wizard";
  const totalSteps = screen.steps?.length || Number(screen.props.totalSteps) || 3;

  let code = `@OptIn(ExperimentalMaterial3Api::class)\n`;
  code += `@Composable\n`;
  code += `fun ${fnName}(\n`;
  code += `    onNavigate: (String) -> Unit = {},\n`;
  code += `    onOpenModal: (String) -> Unit = {},\n`;
  code += `    wizardStep: Int = 1,\n`;
  code += `    onStepChange: (Int) -> Unit = {},\n`;
  code += `    formData: MutableMap<String, Any> = remember { mutableStateMapOf() }\n`;
  code += `) {\n`;

  if (isWizard) {
    code += `    Column(\n`;
    code += `        modifier = Modifier\n`;
    code += `            .fillMaxSize()\n`;
    code += `            .verticalScroll(rememberScrollState())\n`;
    code += `            .padding(16.dp),\n`;
    code += `        verticalArrangement = Arrangement.spacedBy(16.dp)\n`;
    code += `    ) {\n`;
    code += `        // Wizard Header & Stepper Card\n`;
    code += `        ElevatedCard(\n`;
    code += `            modifier = Modifier.fillMaxWidth(),\n`;
    code += `            shape = RoundedCornerShape(24.dp),\n`;
    code += `            colors = CardDefaults.elevatedCardColors(\n`;
    code += `                containerColor = MaterialTheme.colorScheme.surfaceContainer\n`;
    code += `            )\n`;
    code += `        ) {\n`;
    code += `            Column(modifier = Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {\n`;
    code += `                Surface(\n`;
    code += `                    shape = RoundedCornerShape(12.dp),\n`;
    code += `                    color = MaterialTheme.colorScheme.primaryContainer,\n`;
    code += `                    contentColor = MaterialTheme.colorScheme.onPrimaryContainer\n`;
    code += `                ) {\n`;
    code += `                    Text(\n`;
    code += `                        text = "WIZARD • PASO $wizardStep DE ${totalSteps}",\n`;
    code += `                        style = MaterialTheme.typography.labelMedium,\n`;
    code += `                        fontWeight = FontWeight.Bold,\n`;
    code += `                        modifier = Modifier.padding(horizontal = 10.dp, vertical = 4.dp)\n`;
    code += `                    )\n`;
    code += `                }\n`;
    code += `                Text(\n`;
    code += `                    text = "${escapeKotlin(screen.name)}",\n`;
    code += `                    style = MaterialTheme.typography.headlineMedium,\n`;
    code += `                    fontWeight = FontWeight.Bold\n`;
    code += `                )\n`;
    code += `                // Stepper Progress Indicators\n`;
    code += `                Row(\n`;
    code += `                    modifier = Modifier.fillMaxWidth(),\n`;
    code += `                    horizontalArrangement = Arrangement.spacedBy(8.dp),\n`;
    code += `                    verticalAlignment = Alignment.CenterVertically\n`;
    code += `                ) {\n`;
    for (let i = 1; i <= totalSteps; i++) {
      code += `                    FilledIconButton(\n`;
      code += `                        onClick = { onStepChange(${i}) },\n`;
      code += `                        modifier = Modifier.size(36.dp),\n`;
      code += `                        colors = IconButtonDefaults.filledIconButtonColors(\n`;
      code += `                            containerColor = if (wizardStep == ${i}) MaterialTheme.colorScheme.primary else if (wizardStep > ${i}) MaterialTheme.colorScheme.secondaryContainer else MaterialTheme.colorScheme.surfaceVariant\n`;
      code += `                        )\n`;
      code += `                    ) {\n`;
      code += `                        Text("${i}", fontWeight = FontWeight.Bold)\n`;
      code += `                    }\n`;
      if (i < totalSteps) {
        code += `                    LinearProgressIndicator(\n`;
        code += `                        progress = { if (wizardStep > ${i}) 1f else if (wizardStep == ${i}) 0.5f else 0f },\n`;
        code += `                        modifier = Modifier.weight(1f).height(4.dp).clip(CircleShape),\n`;
        code += `                        color = MaterialTheme.colorScheme.primary,\n`;
        code += `                        trackColor = MaterialTheme.colorScheme.surfaceVariant\n`;
        code += `                    )\n`;
      }
    }
    code += `                }\n`;
    code += `            }\n`;
    code += `        }\n\n`;

    code += `        // Wizard Step Content\n`;
    if (screen.steps && screen.steps.length > 0) {
      screen.steps.forEach((st, idx) => {
        code += `        if (wizardStep == ${idx + 1}) {\n`;
        code += `            Column(modifier = Modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(16.dp)) {\n`;
        code += renderComposeNodes(st.children, 4);
        code += `            }\n`;
        code += `        }\n`;
      });
    } else {
      code += renderComposeNodes(screen.children, 2);
    }

    code += `    }\n`;
    code += `}\n\n`;
    return code;
  }

  // Standard Screen
  code += `    Column(\n`;
  code += `        modifier = Modifier\n`;
  code += `            .fillMaxSize()\n`;
  code += `            .verticalScroll(rememberScrollState())\n`;
  code += `            .padding(16.dp),\n`;
  code += `        verticalArrangement = Arrangement.spacedBy(16.dp)\n`;
  code += `    ) {\n`;
  code += renderComposeNodes(screen.children, 2);
  code += `    }\n`;
  code += `}\n\n`;

  return code;
}

/**
 * Recursively converts Wisp AST nodes into Jetpack Compose Material 3 composables.
 */
function renderComposeNodes(nodes: WispNode[], indentLevel: number): string {
  let out = "";
  const pad = "    ".repeat(indentLevel);

  for (const node of nodes) {
    switch (node.type) {
      case "text": {
        const val = escapeKotlin(node.props.value || "");
        const variant = node.props.variant || "body";
        let style = "MaterialTheme.typography.bodyLarge";
        let fontWeight = "FontWeight.Normal";

        if (variant === "display") {
          style = "MaterialTheme.typography.displayMedium";
          fontWeight = "FontWeight.ExtraBold";
        } else if (variant === "headline") {
          style = "MaterialTheme.typography.headlineMedium";
          fontWeight = "FontWeight.Bold";
        } else if (variant === "title") {
          style = "MaterialTheme.typography.titleLarge";
          fontWeight = "FontWeight.SemiBold";
        } else if (variant === "label") {
          style = "MaterialTheme.typography.labelLarge";
          fontWeight = "FontWeight.Medium";
        } else if (variant === "caption") {
          style = "MaterialTheme.typography.bodySmall";
        }

        let color = "MaterialTheme.colorScheme.onSurface";
        if (node.props.color === "primary") color = "MaterialTheme.colorScheme.primary";
        else if (node.props.color === "secondary") color = "MaterialTheme.colorScheme.secondary";
        else if (node.props.color === "error") color = "MaterialTheme.colorScheme.error";

        out += `${pad}Text(\n`;
        out += `${pad}    text = "${val}",\n`;
        out += `${pad}    style = ${style},\n`;
        out += `${pad}    fontWeight = ${fontWeight},\n`;
        out += `${pad}    color = ${color}\n`;
        out += `${pad})\n`;
        break;
      }

      case "button": {
        const label = escapeKotlin(node.props.label || "Action");
        const variant = node.props.variant || "filled";
        const icon = node.props.icon ? mapComposeIcon(node.props.icon) : null;
        const goto = node.props.goto ? `onNavigate("${escapeKotlin(node.props.goto)}")` : "{ /* click */ }";

        let btnComposable = "Button";
        if (variant === "tonal") btnComposable = "FilledTonalButton";
        else if (variant === "outlined") btnComposable = "OutlinedButton";
        else if (variant === "text") btnComposable = "TextButton";
        else if (variant === "elevated") btnComposable = "ElevatedButton";

        out += `${pad}${btnComposable}(\n`;
        out += `${pad}    onClick = ${goto},\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth(),\n`;
        out += `${pad}    shape = RoundedCornerShape(20.dp)\n`;
        out += `${pad}) {\n`;
        if (icon) {
          out += `${pad}    Icon(imageVector = ${icon}, contentDescription = null, modifier = Modifier.size(18.dp))\n`;
          out += `${pad}    Spacer(modifier = Modifier.width(8.dp))\n`;
        }
        out += `${pad}    Text("${label}")\n`;
        out += `${pad}}\n`;
        break;
      }

      case "card": {
        const variant = node.props.variant || "elevated";
        let cardFn = "ElevatedCard";
        if (variant === "outlined") cardFn = "OutlinedCard";
        else if (variant === "filled") cardFn = "Card";

        out += `${pad}${cardFn}(\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth(),\n`;
        out += `${pad}    shape = RoundedCornerShape(24.dp)\n`;
        out += `${pad}) {\n`;
        out += `${pad}    Column(\n`;
        out += `${pad}        modifier = Modifier.padding(20.dp),\n`;
        out += `${pad}        verticalArrangement = Arrangement.spacedBy(12.dp)\n`;
        out += `${pad}    ) {\n`;
        out += renderComposeNodes(node.children, indentLevel + 2);
        out += `${pad}    }\n`;
        out += `${pad}}\n`;
        break;
      }

      case "appbar":
      case "topappbar":
      case "centerappbar": {
        const title = escapeKotlin(node.props.title || "App Title");
        const variant = node.props.variant || "center";
        const icon = mapComposeIcon(node.props.icon || "menu");

        let barName = "CenterAlignedTopAppBar";
        if (variant === "medium") barName = "MediumTopAppBar";
        else if (variant === "large") barName = "LargeTopAppBar";
        else if (variant === "small") barName = "TopAppBar";

        out += `${pad}${barName}(\n`;
        out += `${pad}    title = { Text("${title}", fontWeight = FontWeight.Bold) },\n`;
        out += `${pad}    navigationIcon = {\n`;
        out += `${pad}        IconButton(onClick = { /* menu action */ }) {\n`;
        out += `${pad}            Icon(imageVector = ${icon}, contentDescription = "Menu")\n`;
        out += `${pad}        }\n`;
        out += `${pad}    },\n`;
        out += `${pad}    actions = {\n`;
        out += `${pad}        IconButton(onClick = { /* search */ }) {\n`;
        out += `${pad}            Icon(imageVector = Icons.Default.Search, contentDescription = "Buscar")\n`;
        out += `${pad}        }\n`;
        out += `${pad}        IconButton(onClick = { /* more */ }) {\n`;
        out += `${pad}            Icon(imageVector = Icons.Default.MoreVert, contentDescription = "Más")\n`;
        out += `${pad}        }\n`;
        out += `${pad}    },\n`;
        out += `${pad}    colors = TopAppBarDefaults.topAppBarColors(\n`;
        out += `${pad}        containerColor = MaterialTheme.colorScheme.surfaceContainer\n`;
        out += `${pad}    )\n`;
        out += `${pad})\n`;
        break;
      }

      case "bottomappbar": {
        out += `${pad}BottomAppBar(\n`;
        out += `${pad}    actions = {\n`;
        out += `${pad}        IconButton(onClick = { /* check */ }) { Icon(Icons.Default.Check, contentDescription = null) }\n`;
        out += `${pad}        IconButton(onClick = { /* edit */ }) { Icon(Icons.Default.Edit, contentDescription = null) }\n`;
        out += `${pad}        IconButton(onClick = { /* share */ }) { Icon(Icons.Default.Share, contentDescription = null) }\n`;
        out += `${pad}    },\n`;
        out += `${pad}    floatingActionButton = {\n`;
        out += `${pad}        FloatingActionButton(\n`;
        out += `${pad}            onClick = { /* fab */ },\n`;
        out += `${pad}            containerColor = MaterialTheme.colorScheme.primaryContainer,\n`;
        out += `${pad}            contentColor = MaterialTheme.colorScheme.onPrimaryContainer\n`;
        out += `${pad}        ) {\n`;
        out += `${pad}            Icon(Icons.Default.Add, contentDescription = "Agregar")\n`;
        out += `${pad}        }\n`;
        out += `${pad}    },\n`;
        out += `${pad}    containerColor = MaterialTheme.colorScheme.surfaceContainer\n`;
        out += `${pad})\n`;
        break;
      }

      case "navigationrail":
      case "apprail":
      case "navrail": {
        const hasChildren = node.children && node.children.length > 0;
        const items = hasChildren
          ? node.children
          : [
              { type: "railitem", props: { label: "Inicio", icon: "home" }, children: [] },
              { type: "railitem", props: { label: "Analíticas", icon: "bar-chart-2" }, children: [] },
              { type: "railitem", props: { label: "Ajustes", icon: "settings" }, children: [] },
            ];

        out += `${pad}var selectedRailIndex by remember { mutableIntStateOf(0) }\n`;
        out += `${pad}Row(modifier = Modifier.fillMaxWidth().fillMaxHeight()) {\n`;
        out += `${pad}    NavigationRail(\n`;
        out += `${pad}        modifier = Modifier.fillMaxHeight(),\n`;
        out += `${pad}        containerColor = MaterialTheme.colorScheme.surfaceContainerLow\n`;
        out += `${pad}    ) {\n`;
        if (node.props.fab) {
          const fabIcon = mapComposeIcon(node.props.fab);
          out += `${pad}        FloatingActionButton(\n`;
          out += `${pad}            onClick = { /* fab action */ },\n`;
          out += `${pad}            modifier = Modifier.padding(bottom = 16.dp),\n`;
          out += `${pad}            containerColor = MaterialTheme.colorScheme.primaryContainer\n`;
          out += `${pad}        ) {\n`;
          out += `${pad}            Icon(${fabIcon}, contentDescription = "Acción")\n`;
          out += `${pad}        }\n`;
        }
        items.forEach((item: any, idx: number) => {
          const itemLabel = escapeKotlin(item.props.label || item.props.title || `Item ${idx + 1}`);
          const itemIcon = mapComposeIcon(item.props.icon || "circle");
          out += `${pad}        NavigationRailItem(\n`;
          out += `${pad}            selected = selectedRailIndex == ${idx},\n`;
          out += `${pad}            onClick = { selectedRailIndex = ${idx} },\n`;
          out += `${pad}            icon = { Icon(${itemIcon}, contentDescription = "${itemLabel}") },\n`;
          out += `${pad}            label = { Text("${itemLabel}") }\n`;
          out += `${pad}        )\n`;
        });
        out += `${pad}    }\n`;

        if (hasChildren && node.children.some((c: any) => c.children && c.children.length > 0)) {
          out += `${pad}    Box(modifier = Modifier.weight(1f).fillMaxHeight().padding(16.dp)) {\n`;
          out += `${pad}        when (selectedRailIndex) {\n`;
          node.children.forEach((c: any, idx: number) => {
            out += `${pad}            ${idx} -> Column(modifier = Modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(16.dp)) {\n`;
            if (c.children && c.children.length > 0) {
              out += renderComposeNodes(c.children, indentLevel + 4);
            } else {
              out += `${pad}                Text("${escapeKotlin(c.props.label || c.props.title || "Contenido")}", style = MaterialTheme.typography.titleMedium)\n`;
            }
            out += `${pad}            }\n`;
          });
          out += `${pad}        }\n`;
          out += `${pad}    }\n`;
        }
        out += `${pad}}\n`;
        break;
      }

      case "textfield": {
        const name = escapeKotlin(node.props.name || "input");
        const label = escapeKotlin(node.props.label || name);
        const icon = node.props.icon ? mapComposeIcon(node.props.icon) : null;

        out += `${pad}var text_${name} by remember { mutableStateOf("") }\n`;
        out += `${pad}OutlinedTextField(\n`;
        out += `${pad}    value = text_${name},\n`;
        out += `${pad}    onValueChange = { text_${name} = it; formData["${name}"] = it },\n`;
        out += `${pad}    label = { Text("${label}") },\n`;
        if (icon) {
          out += `${pad}    leadingIcon = { Icon(${icon}, contentDescription = null) },\n`;
        }
        out += `${pad}    shape = RoundedCornerShape(16.dp),\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth()\n`;
        out += `${pad})\n`;
        break;
      }

      case "progress":
      case "loading":
      case "spinner":
      case "linearprogress":
      case "circularprogress": {
        const isCircular = node.type === "circularprogress" || node.type === "spinner" || node.props.variant === "circular";
        const val = node.props.value !== undefined ? Number(node.props.value) / 100 : 0.7;

        if (isCircular) {
          out += `${pad}Box(modifier = Modifier.fillMaxWidth(), contentAlignment = Alignment.Center) {\n`;
          out += `${pad}    CircularProgressIndicator(\n`;
          out += `${pad}        progress = { ${val}f },\n`;
          out += `${pad}        strokeWidth = 6.dp,\n`;
          out += `${pad}        color = MaterialTheme.colorScheme.primary,\n`;
          out += `${pad}        trackColor = MaterialTheme.colorScheme.surfaceVariant\n`;
          out += `${pad}    )\n`;
          out += `${pad}}\n`;
        } else {
          out += `${pad}Column(modifier = Modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(6.dp)) {\n`;
          if (node.props.label) {
            out += `${pad}    Text("${escapeKotlin(node.props.label)}", style = MaterialTheme.typography.labelMedium)\n`;
          }
          out += `${pad}    LinearProgressIndicator(\n`;
          out += `${pad}        progress = { ${val}f },\n`;
          out += `${pad}        modifier = Modifier.fillMaxWidth().height(8.dp).clip(RoundedCornerShape(4.dp)),\n`;
          out += `${pad}        color = MaterialTheme.colorScheme.primary,\n`;
          out += `${pad}        trackColor = MaterialTheme.colorScheme.surfaceVariant\n`;
          out += `${pad}    )\n`;
          out += `${pad}}\n`;
        }
        break;
      }

      case "switch": {
        const name = escapeKotlin(node.props.name || node.id);
        const label = escapeKotlin(node.props.label || name);
        const checked = node.props.checked === true;

        out += `${pad}var switch_${name} by remember { mutableStateOf(${checked}) }\n`;
        out += `${pad}Row(\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),\n`;
        out += `${pad}    horizontalArrangement = Arrangement.SpaceBetween,\n`;
        out += `${pad}    verticalAlignment = Alignment.CenterVertically\n`;
        out += `${pad}) {\n`;
        out += `${pad}    Text("${label}", style = MaterialTheme.typography.bodyLarge)\n`;
        out += `${pad}    Switch(\n`;
        out += `${pad}        checked = switch_${name},\n`;
        out += `${pad}        onCheckedChange = { switch_${name} = it; formData["${name}"] = it }\n`;
        out += `${pad}    )\n`;
        out += `${pad}}\n`;
        break;
      }

      case "checkbox": {
        const name = escapeKotlin(node.props.name || node.id);
        const label = escapeKotlin(node.props.label || name);
        const checked = node.props.checked === true;

        out += `${pad}var check_${name} by remember { mutableStateOf(${checked}) }\n`;
        out += `${pad}Row(\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth().clickable { check_${name} = !check_${name}; formData["${name}"] = check_${name} },\n`;
        out += `${pad}    verticalAlignment = Alignment.CenterVertically,\n`;
        out += `${pad}    horizontalArrangement = Arrangement.spacedBy(8.dp)\n`;
        out += `${pad}) {\n`;
        out += `${pad}    Checkbox(\n`;
        out += `${pad}        checked = check_${name},\n`;
        out += `${pad}        onCheckedChange = { check_${name} = it; formData["${name}"] = it }\n`;
        out += `${pad}    )\n`;
        out += `${pad}    Text("${label}", style = MaterialTheme.typography.bodyMedium)\n`;
        out += `${pad}}\n`;
        break;
      }

      case "slider": {
        const name = escapeKotlin(node.props.name || "slider");
        const min = Number(node.props.min) || 0;
        const max = Number(node.props.max) || 100;
        const val = Number(node.props.value) || 50;

        out += `${pad}var slider_${name} by remember { mutableFloatStateOf(${val}f) }\n`;
        out += `${pad}Column(modifier = Modifier.fillMaxWidth()) {\n`;
        out += `${pad}    Text("${escapeKotlin(node.props.label || name)}: \${slider_${name}.toInt()}", style = MaterialTheme.typography.labelMedium)\n`;
        out += `${pad}    Slider(\n`;
        out += `${pad}        value = slider_${name},\n`;
        out += `${pad}        onValueChange = { slider_${name} = it; formData["${name}"] = it },\n`;
        out += `${pad}        valueRange = ${min}f..${max}f\n`;
        out += `${pad}    )\n`;
        out += `${pad}}\n`;
        break;
      }

      case "chip": {
        const label = escapeKotlin(node.props.label || "Chip");
        const icon = node.props.icon ? mapComposeIcon(node.props.icon) : null;

        out += `${pad}var chipSelected_${node.id} by remember { mutableStateOf(${node.props.selected === true}) }\n`;
        out += `${pad}FilterChip(\n`;
        out += `${pad}    selected = chipSelected_${node.id},\n`;
        out += `${pad}    onClick = { chipSelected_${node.id} = !chipSelected_${node.id} },\n`;
        out += `${pad}    label = { Text("${label}") },\n`;
        if (icon) {
          out += `${pad}    leadingIcon = { Icon(${icon}, contentDescription = null, modifier = Modifier.size(16.dp)) },\n`;
        }
        out += `${pad}    shape = RoundedCornerShape(12.dp)\n`;
        out += `${pad})\n`;
        break;
      }

      case "listitem": {
        const title = escapeKotlin(node.props.title || node.props.label || "Elemento");
        const subtitle = node.props.subtitle ? escapeKotlin(node.props.subtitle) : null;
        const icon = node.props.icon ? mapComposeIcon(node.props.icon) : null;

        out += `${pad}ListItem(\n`;
        out += `${pad}    headlineContent = { Text("${title}", fontWeight = FontWeight.SemiBold) },\n`;
        if (subtitle) {
          out += `${pad}    supportingContent = { Text("${subtitle}") },\n`;
        }
        if (icon) {
          out += `${pad}    leadingContent = { Icon(${icon}, contentDescription = null, tint = MaterialTheme.colorScheme.primary) },\n`;
        }
        out += `${pad}    trailingContent = { Icon(Icons.AutoMirrored.Filled.ArrowForward, contentDescription = null, modifier = Modifier.size(16.dp)) }\n`;
        out += `${pad})\n`;
        break;
      }

      case "divider": {
        out += `${pad}HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp), color = MaterialTheme.colorScheme.outlineVariant)\n`;
        break;
      }

      case "spacer": {
        const h = Number(node.props.size || node.props.height || 16);
        out += `${pad}Spacer(modifier = Modifier.height(${h}.dp))\n`;
        break;
      }

      case "fab": {
        const label = node.props.label ? escapeKotlin(node.props.label) : null;
        const icon = mapComposeIcon(node.props.icon || "plus");

        if (label) {
          out += `${pad}ExtendedFloatingActionButton(\n`;
          out += `${pad}    onClick = { /* fab click */ },\n`;
          out += `${pad}    icon = { Icon(${icon}, contentDescription = null) },\n`;
          out += `${pad}    text = { Text("${label}") },\n`;
          out += `${pad}    containerColor = MaterialTheme.colorScheme.primaryContainer,\n`;
          out += `${pad}    contentColor = MaterialTheme.colorScheme.onPrimaryContainer\n`;
          out += `${pad})\n`;
        } else {
          out += `${pad}FloatingActionButton(\n`;
          out += `${pad}    onClick = { /* fab click */ },\n`;
          out += `${pad}    containerColor = MaterialTheme.colorScheme.primaryContainer,\n`;
          out += `${pad}    contentColor = MaterialTheme.colorScheme.onPrimaryContainer\n`;
          out += `${pad}) {\n`;
          out += `${pad}    Icon(${icon}, contentDescription = null)\n`;
          out += `${pad}}\n`;
        }
        break;
      }

      case "row": {
        out += `${pad}Row(\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth(),\n`;
        out += `${pad}    horizontalArrangement = Arrangement.spacedBy(12.dp),\n`;
        out += `${pad}    verticalAlignment = Alignment.CenterVertically\n`;
        out += `${pad}) {\n`;
        out += renderComposeNodes(node.children, indentLevel + 1);
        out += `${pad}}\n`;
        break;
      }

      case "column": {
        out += `${pad}Column(\n`;
        out += `${pad}    modifier = Modifier.fillMaxWidth(),\n`;
        out += `${pad}    verticalArrangement = Arrangement.spacedBy(12.dp)\n`;
        out += `${pad}) {\n`;
        out += renderComposeNodes(node.children, indentLevel + 1);
        out += `${pad}}\n`;
        break;
      }

      default: {
        if (node.children && node.children.length > 0) {
          out += `${pad}Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {\n`;
          out += renderComposeNodes(node.children, indentLevel + 1);
          out += `${pad}}\n`;
        }
        break;
      }
    }
  }

  return out;
}
